# yaml-language-server: $schema=../node_modules/@infinit-xyz/cli/dist/schemas/config/config.schema.json

project_name: zunxbt
protocol_module: token
chain_info:
  name: Ethereum Mainnet
  short_name: Ethereum
  network_id: 1
  native_currency:
    name: Ethereum
    symbol: ETH
    decimals: 18
  rpc_url: https://1rpc.io/eth
allow_analytics: true

